### ISSUE TITLE
crash on fabric 1.20.1 server

### ISSUE THREAD

**Issue by NitrolessWasTaken** [FoundationGames/MealAPI#8]
using meal api 3.2 and fabric api 0.92.0, no other mods installed, does not happen on client, does not happen on quilt

```
[17:49:31] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mealapi'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.NoSuchFieldError: clientSyncedFullness
at io.github.foundationgames.mealapi.impl.PlayerFullnessUtilImpl.<init>(PlayerFullnessUtilImpl.java:30) ~[mealapi-0.3.2+1.20.jar:?]
at io.github.foundationgames.mealapi.impl.PlayerFullnessUtilImpl.<clinit>(PlayerFullnessUtilImpl.java:24) ~[mealapi-0.3.2+1.20.jar:?]
at io.github.foundationgames.mealapi.MealAPI.onInitialize(MealAPI.java:18) ~[mealapi-0.3.2+1.20.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
... 6 more
```

**Comment by CStafford-14** [comment]
Getting the same thing on my end. I think they just need to update their dependency on the fabric loader.

**Comment by star-whisper9** [comment]
As a temporary solution, you can try using a Fabric Loader version lower than 0.15.0, such as 0.14.25, which is the last minor version of 0.14.

**Comment by XaaRii** [comment]
This is not as simple as "updating the dependency", Meal API requires any fabric loader bigger or equal to version 0.11.0. That means there must've been a breaking change in fabric loader that this mod sadly didn't account for.
Normally I would just downgrade Fabric version, but I have so many mods (like Create) who depend on version 0.15.7+.
